esphome:
  name: c3-ble-proxy
  friendly_name: c3-ble-proxy
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3  
    board_build.flash_mode: dio
  on_boot: #this is to avoid slow startup time because of BT and WiFi "interactions?" , check https://github.com/esphome/issues/issues/2941#issuecomment-1331851692
    - priority: 500
      then:
        - esp32_ble_tracker.stop_scan:
    - priority: 100
      then:
        - delay: 10s
        - esp32_ble_tracker.start_scan:
            continuous: true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"    
      variant: ESP32C3


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EncryptionKey="

ota:
  password: "OtaPassword"

button:
  - platform: safe_mode
    name: "${friendly_name} (Safe Mode)"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: "8.5"  # sometimes results in a bootloop without it

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "C3-Ble-Proxy Fallback Hotspot"
    password: "zIi0XJHynI9l"

captive_portal:

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    continuous: false
    active: True

bluetooth_proxy:
  active: true


